application: t-servi
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
- url: /crossdomain.xml
  static_files: static/crossdomain.xml
  upload: static/crossdomain.xml
- url: /img
  static_dir: static/images
- url: /xinha
  static_dir: static/Xinha_0.95
- url: /.*
  script: index.py



